title = "Natan Santolo"
languagecode = "en_US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://www.natansantolo.com/"

relativeurls = false
canonifyurls = true
watch = true

[author]
  name = "Natan Santolo"

[params]
  description = "Web Craftsman"

[taxonomies]
  category = "categories"
  tag = "tags"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

SectionPagesMenu = "social"

[[menu.social]]
  name = "Twitter"
  identifier = "twitter"
  url = "https://twitter.com/natos"
  pre = "<i class='fa fa-twitter-square'></i>"
  weight = 1
[[menu.social]]
  name = "Github"
  identifier = "github"
  url = "https://github.com/natos"
  pre = "<i class='fa fa-github-square'></i>"
  weight = 2
[[menu.social]]
  name = "LinkedIn"
  identifier = "linkedin"
  url = "https://nl.linkedin.com/in/natansantolo"
  pre = "<i class='fa fa-linkedin-square'></i>"
  weight = 3
[[menu.social]]
  name = "Behance"
  identifier = "behance"
  url = "https://www.behance.net/natansantolo"
  pre = "<i class='fa fa-behance-square'></i>"
  weight = 4
[[menu.social]]
  name = "Tumblr"
  identifier = "tumblr"
  url = "http://natos.tumblr.com"
  pre = "<i class='fa fa-tumblr-square'></i>"
  weight = 5
[[menu.social]]
  name = "Instagram"
  identifier = "instagram"
  url = "https://www.instagram.com/natansantolo/"
  pre = "<i class='fa fa-instagram'></i>"
  weight = 6