baseurl = "https://www.natansantolo.com/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languagecode = "en_US"
layoutdir = "layouts"
publishdir = "public"
relativeurls = false
title = "Natan Santolo"
watch = true
[author]
name = "Natan Santolo"
[blackfriday]
SectionPagesMenu = "social"
angledQuotes = true
extensions = ["hardLineBreak"]
fractions = false
plainIDAnchors = true
[[menu.social]]
identifier = "linkedin"
name = "LinkedIn"
pre = "<i class='fa fa-linkedin-square'></i>"
url = "https://nl.linkedin.com/in/natansantolo"
weight = 1
[params]
Description = "Free-range Design Leader"
[taxonomies]
category = "categories"
tag = "tags"
[frontmatter]
slug = [ "slug", "title" ]
[permalinks]
book = "/:section/:title/"