---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml,toml}"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.17'
